name: julia-env
channels:
  - conda-forge
dependencies:
  - julia
  - pip
  - notebook
  - ipykernel
  - python
  - matplotlib
  - numpy
  - scipy
postBuild:
  - julia -e '
    using Pkg;
    Pkg.add([
      "IJulia",
      "Oceananigans",
      "Plots",
      "DataFrames",
      "CSV",
      "StatsPlots",
      "DifferentialEquations"
    ]);
    Pkg.precompile();'

